# report-config.yml (user editable)
version: 2

# timezone (IANA format)
# Examples: America/New_York, America/Toronto, UTC
# If you're unsure, search: "IANA timezone for <your city>"
timezone: "America/Toronto"

repo_visibility: public   # public | private

mlflow:
  tracking_uri: https://dagshub.com/cyndi-s/accelerate-mlops-test.mlflow/  # https://dagshub.com/<owner>/<repo>.mlflow

report:
  highlight_metric: accuracy
  sharp_delta: 0.03
  trend_window: 10

storage:
  gist_url: "https://gist.github.com/cyndi-s/ece2e2a49f1ce956f1a242b86bb8db50"   # or just paste the gist URL


project:
  train_script: examples/nlp_example.py
  
# optional: system-level dependencies for GitHub Actions runner
  # - This is for apt-get install (binaries/libs), NOT Python pip deps.
  # - Only allowlisted values will be installed by devops-mlops-report.
  # - If missing/unsupported, the tool should warn + continue (best-effort).
  system_deps:
    # - graphviz        # provides `dot` binary (for diagrams)
    # - ffmpeg
    # - opencv_runtime
    # - poppler_utils
    # - tesseract




